### PR TITLE
Full date

### PR DESCRIPTION
**Pull request by avgog**
Added functionality to show the full date on the home page.
It works for both english and dutch.

### CODE REVIEW

**Comment by avgog** [comment]
Link of the excel sheet for your test results: https://docs.google.com/spreadsheets/d/1PeGnw1rvz-zkth0x19UNdDSDeJ--6H91GMnyzJXSmeI/edit#gid=0

**Review by VeeNinetyFour — APPROVED** [review]
The date displays correctly in both English and Dutch.

**Review by Mohamed1651 — APPROVED** [review]
The date displays exactly like it should. Like the way you formatted the date to a full date string. Approved!

**Review by HakanDalama — APPROVED** [review]
date is correct

**Pull request merged**
