### PR TITLE
Modify icons

### PR DESCRIPTION
**Pull request by Mohamed1651**

### CODE REVIEW

**Review by LucasOudhuis — APPROVED** [review]
Looks better

**Review by avgog — CHANGES_REQUESTED** [review]
I don't like the icon of the CMI button (it is a calender icon), please change it (for example to info icon).
I'm content with the other icons.

**Review by avgog — APPROVED** [review]
The CMI button has the right icon with the right size. Approved.

**Review by VeeNinetyFour — APPROVED** [review]
Everything looks good and suitable.

**Pull request merged**
