### PR TITLE
Questionform functionality

### PR DESCRIPTION
**Pull request by HakanDalama**
Ask a question form made functionality

### CODE REVIEW

**Review by LucasOudhuis — APPROVED** [review]
Ziet er goed uit!

**Review by Mohamed1651 — APPROVED** [review]
Ask a question looks good and nice functionalities!

**Review by agrida2 — CHANGES_REQUESTED** [review]
<activity android:name=".MainActivity"> Should stay in the manifest

**Review by LucasOudhuis — APPROVED** [review]
Klopt nu wel denk ik

**Review by agrida2 — APPROVED** [review]

**Pull request merged**
