### PR TITLE
Added toast for validator in question form

### PR DESCRIPTION
**Pull request by Mohamed1651**

### CODE REVIEW

**Comment by Mohamed1651** [comment]
Go to the link to submit your test!
https://docs.google.com/spreadsheets/d/1PeGnw1rvz-zkth0x19UNdDSDeJ--6H91GMnyzJXSmeI/edit#gid=0&range=A43

**Review by avgog — CHANGES_REQUESTED** [review]
-Found a bug: if you open the question form and fill all the fields with valid values, than opening a new question form and than go back to the old question form (with the valid values), you will get a message
that there are invalid fields even tough all fields are valid.
I'm confident that the valids variable of the validator causes this, because that variable is static.
Please fix that. Also, why did you make it static?
-The variable valid (different variable) in the Questionform is not being used, please, remove that variable.
-Strings like "You have some invalid field(s)." should not be hard coded, but needs to be in the strings.xml
file in order to be able to translate them. I also suggest that you do the translation for that string.
-Another bug: If you tap on the send button multiple times quickly when the fields are invalid, the toast message stays on the screen longer than it should be. For example: if I tap on it 10 times when the message is already on the screen, it is visible for like 20 seconds. Also needs to be fixed.
Hint: you might want to use toast.cancel().

**Comment by Mohamed1651** [comment]
Thx changes have been applied!
-Added cancel function to toast
-Removed variable that wasn't being used
-Message added to string.xml with translation to dutch

**Review by agrida2 — APPROVED** [review]

**Review by agrida2 — APPROVED** [review]
Tested and it works fine!!

**Review by HakanDalama — APPROVED** [review]

**Review by avgog — APPROVED** [review]
The bug about the toast message showing up when every field is valid has been fixed.
The time of displaying that message seems to be shorter than before after tapping, I'll count that
as a fix. Approved.

**Pull request merged**
