### PR TITLE
List study programs

### PR DESCRIPTION
**Pull request by Dinesh0966028**
I made a page with all the courses and and every course has his own page plus a link to the internet.

### CODE REVIEW

**Review by agrida2 — APPROVED** [review]
Haven't spotted any conflicts. The changed coded is well written and approved

**Review by Mohamed1651 — APPROVED** [review]
Should work but I do see a potential merge conflict in .idea/misc.xml.

**Review by LucasOudhuis — CHANGES_REQUESTED** [review]
Seeing some duplicate activities in the android manifest

**Review by HakanDalama — COMMENTED** [review]
We are not choosing for this design so please cancel this pull request.

**Comment by avgog** [comment]
Closed pull request because an implementation of the study programs has already been made by
Bastiaan. We have chosen his implementation because 1. he made his pull request earlier and 2.
his implementation is better because he doesn't have a seperate activity + layout for
each study program.

**Pull request closed without merging**
