### PR TITLE
Modified question form layout

### PR DESCRIPTION
**Pull request by avgog**
-Moved the textfields to the left
-Made the message textfield smaller

### CODE REVIEW

**Review by LucasOudhuis — APPROVED** [review]
Looks al lot better

**Review by Dinesh0966028 — APPROVED** [review]
It look great.

**Review by Dinesh0966028 — APPROVED** [review]
I see that you changed the layout. Great job. Nothing to add.

**Review by Mohamed1651 — APPROVED** [review]
Approved!

**Pull request merged**
