### PR TITLE
Azzeddine2

### PR DESCRIPTION
**Pull request by agrida2**

### CODE REVIEW

**Review by VeeNinetyFour — DISMISSED** [review]
I can't launch it at all. There's something wrong in AndroidManifest first of all, but also in other places I don't know about.

I'd suggest testing yourself before you commit.

**Comment by VeeNinetyFour** [comment]
> I can't launch it at all. There's something wrong in AndroidManifest first of all, but also in other places I don't know about.
> 
> I'd suggest testing yourself before you commit.

Forgot to pull. Oops

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Menu is not present on all pages (Study programs list)
Also, the activity that manages the course pages doesn't show at all. (while the menu does)

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
The studypage activity works now, which is great! But the menu is still not accessible from the activity that shows the list of study courses. As well as from the studypages themselves; the button is not clickable. The button "courses" in the menu goes to the CMGT page too :/

 Fix that & instant approve 😄

I'll adjust the letter sizes in a later branch

**Review by avgog — CHANGES_REQUESTED** [review]
-If you press on courses on the sidebar menu, you will go to the detailpage of one of the study courses, but
you are supposed to go to the page with a list of study courses. That needs to be changed.
-Also the sidebar button on the toolbar doesn't work (it won't open the sidebar menu).
-I've also noticed there is another button on the right side on the toolbar on the question form page.
That needs to be removed.

**Review by LucasOudhuis — APPROVED** [review]
Not seeing any bugs

**Review by avgog — APPROVED** [review]
The sidebar works on every page and the button on the right side of the toolbar has been removed on the question form. Approved!

**Review by VeeNinetyFour — APPROVED** [review]
It just... works! Perfectly!

As I said, instant approve. 😄

**Review by Mohamed1651 — APPROVED** [review]
I see that it has no merge conflicts now.

**Review by agrida2 — COMMENTED** [review]
Fonts look nice and u cleared unnecessarily code!

**Pull request merged**
