### PR TITLE
splashscreen

### PR DESCRIPTION
**Pull request by HakanDalama**
made the spashscreen (also changed the manifest that it first starts with the splashscreen and then the mainactivity)

### CODE REVIEW

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
It looks good, but when you press the Back button on the home screen, it goes back to the splash screen and stays there. There's no way to go back to the homescreen without restarting the app,

**Review by VeeNinetyFour — APPROVED** [review]

**Review by avgog — CHANGES_REQUESTED** [review]
It works on my phone without any issues and I like the layout, but there are a few minor changes that need
to be made before approving this request.
-add a few comments to the splash screen activity so other team members are able to understand it.
(what does finish do? what does the postdelayed function do? etc.)
-What also needs to be changed is the version text on the splash screen image. You can't change the text because it is on the image and not on a seperate textview. I suggest you to add a textview on that layout and put the version there (and the string needs to be from string.xml). The second, more simpler solution would be removing the version text from the image.

**Review by avgog — APPROVED** [review]

**Comment by avgog** [comment]
The version text is on a seperate textview and is on the right place on my screen. Approved!

**Review by LucasOudhuis — APPROVED** [review]
Working for me

**Pull request merged**
