### PR TITLE
question form layout change and validation

### PR DESCRIPTION
**Pull request by avgog**
-modified the layout so it looks more like the design.
-added validation for all fields.

### CODE REVIEW

**Review by Dinesh0966028 — APPROVED** [review]
I don't see any problems. You only changed the layout. Great job Audi!

**Comment by avgog** [comment]
> I don't see any problems. You only changed the layout. Great job Audi!

How about the validation?

**Review by Mohamed1651 — APPROVED** [review]
Nice Work! Love the way you did the validation. Something we can use in the future aswell!

**Review by VeeNinetyFour — APPROVED** [review]
There are some unneccesary imports within the code, but everything seems to work fine. Merge!

**Pull request merged**
