### PR TITLE
Database2

### PR DESCRIPTION
**Pull request by LucasOudhuis**
- Database for pop ups
- Database reset at startup app
- Added Dutch databases
- Now checks language on phone and displays correct language

### CODE REVIEW

**Review by avgog — APPROVED** [review]
The app loads (with the right language) the values correctly from the database and puts it
on the homescreen, detailpage and event page without any issues. Approved.

**Review by Dinesh0966028 — COMMENTED** [review]
the app works with the right language. Misschien kun je wel het woord "kamer" veranderen naar "lokaal".

**Review by Dinesh0966028 — APPROVED** [review]
Good job!
I see you changed the string from kamer to lokaal.

**Review by VeeNinetyFour — APPROVED** [review]
There are some minor mistranslations ("Time" on the homepage and a string on the popup) but I believe the latter has been fixed in another branch, so I'll approve.

**Pull request merged**
