### PR TITLE
Notepad and eventlayout

### PR DESCRIPTION
**Pull request by Dinesh0966028**
fixed layout plus toolbar

### CODE REVIEW

**Review by VeeNinetyFour — COMMENTED** [review]
Toolbar and sidebar menu work, but I suggest putting a margin Left and Right to the TextViews within the ScrollView.

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Please implement a margin.

**Comment by avgog** [comment]
Made commits for supporting night mode on both layouts. Don't forget to test that too.

**Review by avgog — CHANGES_REQUESTED** [review]
Requested changes:
-on the event page, add margin to the left side of the text. It's text is already touching the border
of my screen.
-The top part of the communication image is on the CMGT section on both open days. Fix that.
-The buttons are on top of the text of project examples, at least on my device.
I suggest you fix that by putting the buttons in the linearlayout vertical (which is in the scrollview).

image

**Review by avgog — CHANGES_REQUESTED** [review]
Requested changes:
-The bottom part of the background doesn't move when scrolling up/down.
It needs to be moved with the content of the page when scrolling.
Or it needs to be removed.
-Text isn't white on dark mode on the event page. Change that.
-On both open days detail pages, the spaces between the study course sections are white when
they are supposed to have a darker color. The color of the black lines when on dark mode also needs
to be changed.

Hint: change the color (textColor/background) properties with these values:
?attr/textcolor for the text
?attr/backgroundcolor for the space on the detailpage.
?attr/backgroundcolor2 for the line on each space.

**Comment by avgog** [comment]
You will see the bottom part more clearly on dark mode.

**Review by avgog — APPROVED** [review]
All my change requests has been approved. No issues met during testing. Approved!

**Review by HakanDalama — APPROVED** [review]
tested it and the changes have been done sucessfully good job

**Review by VeeNinetyFour — APPROVED** [review]
Margin looks good. Everything works. No problems!

**Pull request merged**
