### PR TITLE
Floorplan buttons round corners

### PR DESCRIPTION
**Pull request by avgog**
Made the corners of the buttons round.

### CODE REVIEW

**Review by Dinesh0966028 — APPROVED** [review]
Well done Audi!
The buttons look great.

**Review by LucasOudhuis — APPROVED** [review]
Looking good Audi

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Everything looks good, but please make it so that the button of the currently selected building is disabled (not pressable).

**Review by VeeNinetyFour — APPROVED** [review]
Great! Buttons are disabled at the appropriate times.

**Pull request merged**
