### PR TITLE
Credits page

### PR DESCRIPTION
**Pull request by VeeNinetyFour**
Done!

### CODE REVIEW

**Review by agrida2 — DISMISSED** [review]
Works and looks fine!

**Review by avgog — CHANGES_REQUESTED** [review]
Cannot build and run the program because of the unreachable statement error in the menu_activity page.
That needs to be fixed.
Also the code beneath the credits switch case is of the nightmode case, which is ABOVE the credits statement.
Because of that, the nightmode will not work.

**Review by Dinesh0966028 — CHANGES_REQUESTED** [review]
I tried to run the app but it gave errors.

I got this in my screen:

error: unreachable statement

and there is a problem with the compile. ( I actually don't what compile is)

**Comment by avgog** [comment]
> Works and looks fine!

How come that you can run the app when me and Dinesh can't even compile it?

**Review by HakanDalama — COMMENTED** [review]
maybe you have to look if the app works because on my laptop it doesnt even start anymore it says that the app keeps crashing after the splashscreen

**Review by avgog — CHANGES_REQUESTED** [review]
I'm happy with the change you made previously requested, but there are a few more things you need to
do before I'm going to approve this pull request:
-The imageview is causing lag when scrolling. I already found the solution which is reducing the size
(width x height, not file size) of the image. I've done that myself (reducing it to 50% of its size) and the lag is gone. Task: the lag needs to be fixed.
-Change the icon of the Credits on the sidebar, because it is the same icon as of the CMI page.
You might want to use this icon instead: https://www.google.com/search?safe=active&rlz=1C1AVFC_enNL812NL812&biw=1920&bih=969&tbm=isch&sa=1&ei=-3H5XJiMJ4jekgX-io-QDw&q=team+icon+png&oq=team+icon+png&gs_l=img.3..0j0i5i30l5j0i5i10i30j0i5i30j0i8i30l2.932637.933648..934187...0.0..1.449.873.1j1j1j0j1......0....1..gws-wiz-img.......0i30.lcc17iy95v4#imgrc=EhOWPdV3rGP8OM: 
(Or try to find a better one)
It needs to be displayed correctly in day and nightmode.

**Review by avgog — APPROVED** [review]
There's no lag anymore with the scrolling and the I like the new icon.
The icon works both in day and night mode. Approved!

**Comment by avgog** [comment]
Night mode support for the credits page has been added.

**Review by Dinesh0966028 — APPROVED** [review]
The credits page works just fine.
Well done!

**Review by LucasOudhuis — CHANGES_REQUESTED** [review]
When I try to open the ask a question activity the app crashes

**Review by LucasOudhuis — APPROVED** [review]
Problem with test phone

**Pull request merged**
