### PR TITLE
Database add

### PR DESCRIPTION
**Pull request by agrida2**

### CODE REVIEW

**Review by LucasOudhuis — CHANGES_REQUESTED** [review]
Not going to accept this

**Review by Mohamed1651 — CHANGES_REQUESTED** [review]
THIS IS UNACCEPTABLE!!!!! WHAT DID YOU CHANGE!!!

**Comment by avgog** [comment]
What do you want us to test and how can get on the page for adding an open day?
Also, you should only make a pull request if you are done with your tasks.

**Comment by avgog** [comment]
Solve the conflicts first if you want me to review this pull request.

**Review by LucasOudhuis — APPROVED** [review]
Change the XML file in openday3 to open_day_layout

**Review by VeeNinetyFour — APPROVED** [review]
It works... I guess. It's extremely user-unfriendly, but it does what it's supposed to do as far as I can tell

**Review by Mohamed1651 — APPROVED** [review]

**Pull request merged**
