### PR TITLE
share popup

### PR DESCRIPTION
**Pull request by Dinesh0966028**
I made a new share pop up. 
I changed for every pop up background.
There are still some problems with the buttons. 
If you don't have the app the app crashes. 
So the code needs actually a check to see if you have for example the facebook app.

### CODE REVIEW

**Review by avgog — CHANGES_REQUESTED** [review]
There are a few changed you need to make before I'm willing to approve this pull request:
-The button for showing the share pop up doesn't work on the second open day.
-You have to copy the message manually and paste it on your app of choice. This needs to happen
automatically after the user has pressed on one of the apps.
-Add more comments to your PopShareActivity class.
-Before opening the app, check if it exists. If not, than notify the user doesn't have that app of choice
on his phone. The app should not crash.

Positive feedback:
-I'm content with the share pop up layout.
-I agree with your choice of supported apps for sharing.

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Same as Audi. App crashes when an app is chosen that does not exist. See if Java has an equivalent to the Python operator "try"

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Instead of being a share function, the buttons simply opens the app without giving any further instructions. Furthermore, if Whatsapp is not installed on the device, the app still crashes. (Others are opened in the browser, which is a good solution.)

I would suggest checking if the app is installed on the system _before_ trying to open it; you could use an equivalent of the python "try" operator, perhaps?

**Review by avgog — APPROVED** [review]
The sharing works on both open days, you don't get too much choices of apps for sharing anymore.
The share pop up and the sharing functionality works flawlessly without any issues. Because of the fact
that it works, I'm going to approve this. However, I would have liked if you did add some comments to your code. Do that next time, please.

**Review by VeeNinetyFour — APPROVED** [review]
Works well enough. Facebook is not entirely correct, but it works well enough to approve.

**Review by HakanDalama — APPROVED** [review]
the popups are looking good, it is nice that the background is dark, and that you only choose specific apps

**Pull request merged**
