### PR TITLE
Share event

### PR DESCRIPTION
**Pull request by Dinesh0966028**
I made the share event function and the add to calendar function.
(can someone else update my branch because I can't access my master anymore

### CODE REVIEW

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
The app doesn't compile, activity_pop.xml is a mess.

**Review by avgog — CHANGES_REQUESTED** [review]
Same as Bastiaan, can't compile either.

**Review by VeeNinetyFour — APPROVED** [review]
Not all names are correct (Software & Computer Engineering), but it works and is good enough for me.

**Review by Mohamed1651 — APPROVED** [review]
Werkt slimme idee om textview te gebruiken.

**Review by avgog — APPROVED** [review]

**Pull request merged**
