### PR TITLE
Night mode

### PR DESCRIPTION
**Pull request by avgog**
-Added seperate colors for night mode
-Toggle of the night mode is on the sidebar

### CODE REVIEW

**Comment by avgog** [comment]
test result sheet link: https://docs.google.com/spreadsheets/d/1PeGnw1rvz-zkth0x19UNdDSDeJ--6H91GMnyzJXSmeI/edit#gid=0

**Review by VeeNinetyFour — APPROVED** [review]
Some colours could be changed for clarity and aesthetic reasons, but that's something for next sprint.

**Review by HakanDalama — APPROVED** [review]
looks good i approve

**Review by agrida2 — APPROVED** [review]
Looks good!

**Pull request merged**
