### PR TITLE
Database2

### PR DESCRIPTION
**Pull request by LucasOudhuis**
Everything working except for the popups(app kept crashing)

### CODE REVIEW

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Does not compile.

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Database seems to work. App crashes on startup on emulator.

**Review by Mohamed1651 — APPROVED** [review]
This does work but you should still have to try to find a way to add the text from popups to the database. I'll approve the code you've shown for now.

**Review by VeeNinetyFour — APPROVED** [review]
Same as Mo. System works!

**Review by avgog — APPROVED** [review]
The open days and events are loaded from the database and displayed succesfully with no issues.
I would like that you add more comments to your code but I can understand your code. Approved.

**Comment by avgog** [comment]
*events -> open day details

**Pull request merged**
