### PR TITLE
login page

### PR DESCRIPTION
**Pull request by HakanDalama**
made the loginpage

### CODE REVIEW

**Review by Mohamed1651 — APPROVED** [review]
Login Works great. Admin can login and other accounts cannot. Works like it should. I approve.

**Review by VeeNinetyFour — CHANGES_REQUESTED** [review]
Please create a button to lead to the admin login page, so that I can test it (and it actually qualifies as a completed feature)!

**Review by VeeNinetyFour — COMMENTED** [review]
Nice work! Everything works as it should.

**Review by VeeNinetyFour — APPROVED** [review]
Everything works as intended. Nice work!

**Review by Dinesh0966028 — APPROVED** [review]
Nice done Hakan! 
I have tested the login page and it works!
I also helped you with the toast, because it also appeared when you did log in. 
But we fixed it.

**Pull request merged**
